site_name: "SAREhub"
pages:
- Wstęp: 'index.md'
- System: 'system.md'
- Zdarzenia: 'event.md'
- Podstawowe typy zdarzeń: 'typesOfEvents.md'
- Integracja: 'integration.md'
theme: united
extra_css:
- css/extra.css